spring:
  security:
    user:
      name: bff-client
      password: password
application:
  internal:
    mobile-privilege:
      security:
        username: mobile-privilege-client
        password: password
  retry:
    maxAttempts: 3
    backOff: 2000
  async:
    delayTimeInSeconds: 5
